ExoRobiSite/Models/CommunicationHandler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExoRobiSite.Models
{
    public class CommunicationHandler
    {
        public void SaveCommand()
        {

        }
        public void GetCommand()
        {

        }
        public void GetQueue()
        {

        }
        public void SaveQueue()
        {

        }
    }
}

ExoRobiSite/Models/CommunicationModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExoRobiSite.Models
{
    public class CommunicationModel
    {
        public string Command { get; set; }
        public List<string> CommandQueue { get; set; }
    }
}

ExoRobiSite/Models/ICommunication.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExoRobiSite.Models
{
    interface ICommunication
    {
    }
}

ExoRobiSite/Models/ICrypto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExoRobiSite.Models
{
    interface ICrypto
    {
    }
}

ExoRobiSite/Models/IDataReader.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExoRobiSite.Models
{
    interface IDataReader
    {
    }
}

ExoRobiSite/Models/ILoginValidation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExoRobiSite.Models
{
    interface ILoginValidation
    {

    }
}

ExoRobiSite/Models/LoginHandler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExoRobiSite.Models
{
    public class LoginHandler
    {

    }
}

ExoRobiSite/Models/LoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExoRobiSite.Models
{
    public class LoginModel
    {
    }
}

ExoRobiSite/Models/RefHandler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExoRobiSite.Models
{
    public class RefHandler
    {
    }
}

ExoRobiSite/Models/RefModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExoRobiSite.Models
{
    public class RefModel
    {
    }
}

ExoRobiSite/Controllers/ExoSiteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExoRobiSite.Controllers
{
    public class ExoSiteController : Controller
    {
        public ActionResult Main()
        {
            return View();
        }
    }
}

ExoRobiSite/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExoRobiSite.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
    }
}

ExoRobiSite/Controllers/RefController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExoRobiSite.Controllers
{
    public class RefController : Controller
    {
        // GET: Ref
        public ActionResult Index()
        {
            return View();
        }
    }
}

ExoRobiSite/Views/ExoSite/Main.cshtml
@model ExoRobiSite.Models.CommunicationModel

@{
    ViewBag.Title = "Main";
}


    <div style="width:1800px; margin-left:auto; margin-right:auto;">
        <div style="display:grid; ">
            <div class="row" style="height:600px">
                <div class="col-sm-1 bg-primary" style="width:15%">
                    <p>1</p>
                </div>
                <div class="col-sm-1 text-center" style="width:70%">
                    <p>2</p>
                </div>
                <div class="col-sm-1 bg-primary" style="width:15%">
                    <p>3</p>
                </div>
            </div>
            <div class="row" style="height:250px">
                <div class="col-sm-1 bg-primary" style="width:60%">
                    <input id="commandInput" class="" type="text" style="width:300%;"/>
                </div>
                <div class="col-sm-1" style="width:20%">
                    <p>5</p>
                </div>
                <div class="col-sm-1 bg-primary" style="width:20%">
                    <p>6</p>
                </div>
            </div>
        </div>
    </div>

ExoRobiSite/Views/Ref/Index.cshtml
@{
    ViewBag.Title = "RefSite";
}

ExoRobiSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ExoRobi - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:dimgrey">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ExoRobi", "Main", "ExoSite", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ref Side", "Index", "Ref")</li>
                    <li></li>
                </ul>
            </div>
        </div>
    </div>
    <div>
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>